name: CI
on: [push, pull_request]

permissions: {}

jobs:
  lint-actions:
    name: GitHub Actions audit
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run actionlint
        uses: rhysd/actionlint@393031adb9afb225ee52ae2ccd7a5af5525e03e8 # v1.7.11

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@71321a20a9ded102f6e9ce5718a2fcec2c4f70d8 # v0.5.2
        with:
          advanced-security: false

  tests:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      matrix:
        ruby: ["3.4", "4.0"]
        gemfile:
          - gemfiles/rails_8.1.gemfile
          - gemfiles/rails_main.gemfile

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@319994f95fa847cf3fb3cd3dbe89f6dcde9f178f # v1.295.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install LibreOffice
        run: |
          sudo apt-get update
          sudo apt-get install -y libreoffice libvips

      - name: Run tests
        run: bundle exec rake test
