name: CI
on: [push, pull_request]

permissions: {}

jobs:
  lint-actions:
    name: GitHub Actions audit
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run actionlint
        uses: rhysd/actionlint@914e7df21a07ef503a81201c76d2b11c789d3fca # v1.7.12

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@71321a20a9ded102f6e9ce5718a2fcec2c4f70d8 # v0.5.2
        with:
          advanced-security: false

  tests:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      matrix:
        ruby: ["3.4", "4.0"]
        gemfile:
          - gemfiles/rails_8.1.gemfile
          - gemfiles/rails_main.gemfile

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@e65c17d16e57e481586a6a5a0282698790062f92 # v1.300.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install LibreOffice
        run: |
          sudo apt-get update
          sudo apt-get install -y libreoffice libvips

      - name: Run tests
        run: bundle exec rake test
